spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/gestionaleimmobiliare
    username: immobiliare
    password: immobiliare
  jpa:
    open-in-view: false
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
  web:
    resources:
      chain:
        enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: andrea@mediacy.it
    password: dyykkhfxojibkqqf
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          from: andrea@mediacy.it
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
        port: 587
  quartz:
    enabled: true
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
    wait-for-jobs-to-complete-on-shutdown: true
    properties:
      org:
        quartz:
          scheduler:
            instanceName: StartScheduler
            instanceId: AUTO
            instanceIdGenerator:
              class: it.andrea.start.quartz.QuartzInstanceIdGenerator
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 20
            threadPriority: 5
            makeThreadsDaemons: true
          jobStore:
            misfireThreshold: 60000
            class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
            useProperties: true
            tablePrefix: public.qrtz_
            isClustered: true
            clusterCheckinInterval: 1000
          plugin:
            shutdownHook:
              class: org.quartz.plugins.management.ShutdownHookPlugin
              cleanShutdown: true
server:
  port: 8081
  servlet:
    context-path: /start
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: INFO
    web: DEBUG
jwt:
  secret: 179069f5c6ee9380faefc1f6e233e0a99bd0ed03ff389829eb6bb6fa4c7a846c
  expiration:
    days: 1
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /api-docs/documentation.html
    operationsSorter: method
    display-request-duration: true
app:
  swagger:
    baseurl: http://localhost:8081/start
    baseurl-https: https://localhost:8081/start
  static:
    path: D:\\gestionale-immobiliare\\resource\\initialize\\
  initialize:
    file:
      path: D:\\gestionale-immobiliare\\resource\\initialize\\
  key:
    offuscator:
      path: D:\\gestionale-immobiliare\\key\\
  media:
    path: D:\\gestionale-immobiliare\\resource\\initialize\\
  template:
    path: D:\\gestionale-immobiliare\\resource\\initialize\\
  logs:
    path: D:\\gestionale-immobiliare\\resource\\initialize\\
  audit:
    level: ALL
    day: 10